### ISSUE TITLE
What license is this?

### ISSUE THREAD

**Issue by unixorn** [horosgrisa/ZPM#2]
I want to add it to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list, but there isn't a license file.

**Comment by horosgrisa** [comment]
@unixorn MIT

**Comment by unixorn** [comment]
OK, I'm not sure how I overlooked LICENSE, sorry.

Looking - LICENSE says it is GPLv3...

**Comment by horosgrisa** [comment]
I do not know much about licenses :smile:

**Comment by unixorn** [comment]
Doesn't matter to me either way, just wanted to let you know.

**Comment by unixorn** [comment]
Also, added it to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) now that I saw the LICENSE
