### ISSUE TITLE
themes?

### ISSUE THREAD

**Issue by SolarAquarion** [horosgrisa/zpm#3]
How do i enable a theme in zpm?

**Comment by horosgrisa** [comment]
It's imposible because themes contradict main idea of this zpm. you need themselves customize  themes.

**Comment by SolarAquarion** [comment]
@horosgrisa how would i do prompt stuff in zpm

**Comment by horosgrisa** [comment]
You can customize your .zshrc . Set `PROMPT` and `RPROMPT` as you want.
