### ISSUE TITLE
Allow configuration of pygmentize colorscheme, in color plugin.

### ISSUE THREAD

**Issue by tomprince** [horosgrisa/zpm#5]
The default theme has some unreadable colors, with a solarized color palaete.

**Comment by horosgrisa** [comment]
pygmentize by default have some color palettes, but no one doesn't look good with solarized 
```
autumn
borland
bw
colorful
default
emacs
friendly
fruity
igor
manni
monokai
murphy
native
paraiso_dark
paraiso_light
pastie
perldoc
rrt
tango
trac
vim
vs
xcode
```
But I use `solarizeddark`  palette, but you need install it separately.
```
sudo pip install pygments-style-solarized
```
https://pypi.python.org/pypi/pygments-style-solarized

**Comment by tomprince** [comment]
I know there are different styles to choose. What I'd like is a way to configure the style used, when using the bundled `colors` plugin.

**Comment by horosgrisa** [comment]
OK. I will add possibility to change pygmentize colorscheme

**Comment by horosgrisa** [comment]
Done. Now you can select pygmentize theme. See https://github.com/horosgrisa/zpm/blob/master/zshrc-example#L76
